// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Securebaseline
{
    [SecurebaselineResourceType("securebaseline:index:CloudwatchApiAudit")]
    public partial class CloudwatchApiAudit : Pulumi.ComponentResource
    {
        /// <summary>
        /// Create a CloudwatchApiAudit resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CloudwatchApiAudit(string name, CloudwatchApiAuditArgs args, ComponentResourceOptions? options = null)
            : base("securebaseline:index:CloudwatchApiAudit", name, args ?? new CloudwatchApiAuditArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/jaxxstorm/pulumi-aws-securebaseline/releases/download/${VERSION}",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class CloudwatchApiAuditArgs : Pulumi.ResourceArgs
    {
        [Input("cloudTrailLogGroupName", required: true)]
        public Input<string> CloudTrailLogGroupName { get; set; } = null!;

        [Input("enableAuthorizedApiCallsAlarm")]
        public Input<bool>? EnableAuthorizedApiCallsAlarm { get; set; }

        [Input("enableAwsConfigChangesAlarm")]
        public Input<bool>? EnableAwsConfigChangesAlarm { get; set; }

        [Input("enableCmkModificationAlarm")]
        public Input<bool>? EnableCmkModificationAlarm { get; set; }

        [Input("enableConsoleSigninFailureAlarm ")]
        public Input<bool>? EnableConsoleSigninFailureAlarm  { get; set; }

        [Input("enableConsoleSigninWithoutMfaAlarm")]
        public Input<bool>? EnableConsoleSigninWithoutMfaAlarm { get; set; }

        [Input("enableIamChangesAlarm")]
        public Input<bool>? EnableIamChangesAlarm { get; set; }

        [Input("enableNaclChangeAlarm")]
        public Input<bool>? EnableNaclChangeAlarm { get; set; }

        [Input("enableNetworkGwChangesAlarm")]
        public Input<bool>? EnableNetworkGwChangesAlarm { get; set; }

        [Input("enableOrganizationsChangesAlarm")]
        public Input<bool>? EnableOrganizationsChangesAlarm { get; set; }

        [Input("enableRootAccountUsageAlarm")]
        public Input<bool>? EnableRootAccountUsageAlarm { get; set; }

        [Input("enableRouteTableChangesAlarm")]
        public Input<bool>? EnableRouteTableChangesAlarm { get; set; }

        [Input("enableS3BucketPolicyChangesAlarm")]
        public Input<bool>? EnableS3BucketPolicyChangesAlarm { get; set; }

        [Input("enableSecurityGroupChangesAlarm")]
        public Input<bool>? EnableSecurityGroupChangesAlarm { get; set; }

        [Input("enableVpcChangesAlarm")]
        public Input<bool>? EnableVpcChangesAlarm { get; set; }

        public CloudwatchApiAuditArgs()
        {
        }
    }
}
