// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package securebaseline

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CloudwatchApiAudit struct {
	pulumi.ResourceState
}

// NewCloudwatchApiAudit registers a new resource with the given unique name, arguments, and options.
func NewCloudwatchApiAudit(ctx *pulumi.Context,
	name string, args *CloudwatchApiAuditArgs, opts ...pulumi.ResourceOption) (*CloudwatchApiAudit, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CloudTrailLogGroupName == nil {
		return nil, errors.New("invalid value for required argument 'CloudTrailLogGroupName'")
	}
	var resource CloudwatchApiAudit
	err := ctx.RegisterRemoteComponentResource("securebaseline:index:CloudwatchApiAudit", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type cloudwatchApiAuditArgs struct {
	CloudTrailLogGroupName             string `pulumi:"cloudTrailLogGroupName"`
	EnableAuthorizedApiCallsAlarm      *bool  `pulumi:"enableAuthorizedApiCallsAlarm"`
	EnableAwsConfigChangesAlarm        *bool  `pulumi:"enableAwsConfigChangesAlarm"`
	EnableCmkModificationAlarm         *bool  `pulumi:"enableCmkModificationAlarm"`
	EnableConsoleSigninFailureAlarm    *bool  `pulumi:"enableConsoleSigninFailureAlarm "`
	EnableConsoleSigninWithoutMfaAlarm *bool  `pulumi:"enableConsoleSigninWithoutMfaAlarm"`
	EnableIamChangesAlarm              *bool  `pulumi:"enableIamChangesAlarm"`
	EnableNaclChangeAlarm              *bool  `pulumi:"enableNaclChangeAlarm"`
	EnableNetworkGwChangesAlarm        *bool  `pulumi:"enableNetworkGwChangesAlarm"`
	EnableOrganizationsChangesAlarm    *bool  `pulumi:"enableOrganizationsChangesAlarm"`
	EnableRootAccountUsageAlarm        *bool  `pulumi:"enableRootAccountUsageAlarm"`
	EnableRouteTableChangesAlarm       *bool  `pulumi:"enableRouteTableChangesAlarm"`
	EnableS3BucketPolicyChangesAlarm   *bool  `pulumi:"enableS3BucketPolicyChangesAlarm"`
	EnableSecurityGroupChangesAlarm    *bool  `pulumi:"enableSecurityGroupChangesAlarm"`
	EnableVpcChangesAlarm              *bool  `pulumi:"enableVpcChangesAlarm"`
}

// The set of arguments for constructing a CloudwatchApiAudit resource.
type CloudwatchApiAuditArgs struct {
	CloudTrailLogGroupName             pulumi.StringInput
	EnableAuthorizedApiCallsAlarm      pulumi.BoolPtrInput
	EnableAwsConfigChangesAlarm        pulumi.BoolPtrInput
	EnableCmkModificationAlarm         pulumi.BoolPtrInput
	EnableConsoleSigninFailureAlarm    pulumi.BoolPtrInput
	EnableConsoleSigninWithoutMfaAlarm pulumi.BoolPtrInput
	EnableIamChangesAlarm              pulumi.BoolPtrInput
	EnableNaclChangeAlarm              pulumi.BoolPtrInput
	EnableNetworkGwChangesAlarm        pulumi.BoolPtrInput
	EnableOrganizationsChangesAlarm    pulumi.BoolPtrInput
	EnableRootAccountUsageAlarm        pulumi.BoolPtrInput
	EnableRouteTableChangesAlarm       pulumi.BoolPtrInput
	EnableS3BucketPolicyChangesAlarm   pulumi.BoolPtrInput
	EnableSecurityGroupChangesAlarm    pulumi.BoolPtrInput
	EnableVpcChangesAlarm              pulumi.BoolPtrInput
}

func (CloudwatchApiAuditArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudwatchApiAuditArgs)(nil)).Elem()
}

type CloudwatchApiAuditInput interface {
	pulumi.Input

	ToCloudwatchApiAuditOutput() CloudwatchApiAuditOutput
	ToCloudwatchApiAuditOutputWithContext(ctx context.Context) CloudwatchApiAuditOutput
}

func (*CloudwatchApiAudit) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudwatchApiAudit)(nil)).Elem()
}

func (i *CloudwatchApiAudit) ToCloudwatchApiAuditOutput() CloudwatchApiAuditOutput {
	return i.ToCloudwatchApiAuditOutputWithContext(context.Background())
}

func (i *CloudwatchApiAudit) ToCloudwatchApiAuditOutputWithContext(ctx context.Context) CloudwatchApiAuditOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudwatchApiAuditOutput)
}

// CloudwatchApiAuditArrayInput is an input type that accepts CloudwatchApiAuditArray and CloudwatchApiAuditArrayOutput values.
// You can construct a concrete instance of `CloudwatchApiAuditArrayInput` via:
//
//          CloudwatchApiAuditArray{ CloudwatchApiAuditArgs{...} }
type CloudwatchApiAuditArrayInput interface {
	pulumi.Input

	ToCloudwatchApiAuditArrayOutput() CloudwatchApiAuditArrayOutput
	ToCloudwatchApiAuditArrayOutputWithContext(context.Context) CloudwatchApiAuditArrayOutput
}

type CloudwatchApiAuditArray []CloudwatchApiAuditInput

func (CloudwatchApiAuditArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudwatchApiAudit)(nil)).Elem()
}

func (i CloudwatchApiAuditArray) ToCloudwatchApiAuditArrayOutput() CloudwatchApiAuditArrayOutput {
	return i.ToCloudwatchApiAuditArrayOutputWithContext(context.Background())
}

func (i CloudwatchApiAuditArray) ToCloudwatchApiAuditArrayOutputWithContext(ctx context.Context) CloudwatchApiAuditArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudwatchApiAuditArrayOutput)
}

// CloudwatchApiAuditMapInput is an input type that accepts CloudwatchApiAuditMap and CloudwatchApiAuditMapOutput values.
// You can construct a concrete instance of `CloudwatchApiAuditMapInput` via:
//
//          CloudwatchApiAuditMap{ "key": CloudwatchApiAuditArgs{...} }
type CloudwatchApiAuditMapInput interface {
	pulumi.Input

	ToCloudwatchApiAuditMapOutput() CloudwatchApiAuditMapOutput
	ToCloudwatchApiAuditMapOutputWithContext(context.Context) CloudwatchApiAuditMapOutput
}

type CloudwatchApiAuditMap map[string]CloudwatchApiAuditInput

func (CloudwatchApiAuditMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudwatchApiAudit)(nil)).Elem()
}

func (i CloudwatchApiAuditMap) ToCloudwatchApiAuditMapOutput() CloudwatchApiAuditMapOutput {
	return i.ToCloudwatchApiAuditMapOutputWithContext(context.Background())
}

func (i CloudwatchApiAuditMap) ToCloudwatchApiAuditMapOutputWithContext(ctx context.Context) CloudwatchApiAuditMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudwatchApiAuditMapOutput)
}

type CloudwatchApiAuditOutput struct{ *pulumi.OutputState }

func (CloudwatchApiAuditOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudwatchApiAudit)(nil)).Elem()
}

func (o CloudwatchApiAuditOutput) ToCloudwatchApiAuditOutput() CloudwatchApiAuditOutput {
	return o
}

func (o CloudwatchApiAuditOutput) ToCloudwatchApiAuditOutputWithContext(ctx context.Context) CloudwatchApiAuditOutput {
	return o
}

type CloudwatchApiAuditArrayOutput struct{ *pulumi.OutputState }

func (CloudwatchApiAuditArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudwatchApiAudit)(nil)).Elem()
}

func (o CloudwatchApiAuditArrayOutput) ToCloudwatchApiAuditArrayOutput() CloudwatchApiAuditArrayOutput {
	return o
}

func (o CloudwatchApiAuditArrayOutput) ToCloudwatchApiAuditArrayOutputWithContext(ctx context.Context) CloudwatchApiAuditArrayOutput {
	return o
}

func (o CloudwatchApiAuditArrayOutput) Index(i pulumi.IntInput) CloudwatchApiAuditOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudwatchApiAudit {
		return vs[0].([]*CloudwatchApiAudit)[vs[1].(int)]
	}).(CloudwatchApiAuditOutput)
}

type CloudwatchApiAuditMapOutput struct{ *pulumi.OutputState }

func (CloudwatchApiAuditMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudwatchApiAudit)(nil)).Elem()
}

func (o CloudwatchApiAuditMapOutput) ToCloudwatchApiAuditMapOutput() CloudwatchApiAuditMapOutput {
	return o
}

func (o CloudwatchApiAuditMapOutput) ToCloudwatchApiAuditMapOutputWithContext(ctx context.Context) CloudwatchApiAuditMapOutput {
	return o
}

func (o CloudwatchApiAuditMapOutput) MapIndex(k pulumi.StringInput) CloudwatchApiAuditOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudwatchApiAudit {
		return vs[0].(map[string]*CloudwatchApiAudit)[vs[1].(string)]
	}).(CloudwatchApiAuditOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudwatchApiAuditInput)(nil)).Elem(), &CloudwatchApiAudit{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudwatchApiAuditArrayInput)(nil)).Elem(), CloudwatchApiAuditArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudwatchApiAuditMapInput)(nil)).Elem(), CloudwatchApiAuditMap{})
	pulumi.RegisterOutputType(CloudwatchApiAuditOutput{})
	pulumi.RegisterOutputType(CloudwatchApiAuditArrayOutput{})
	pulumi.RegisterOutputType(CloudwatchApiAuditMapOutput{})
}
