// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./cloudwatchApiAudit";
export * from "./foo";
export * from "./provider";
export * from "./vpc";

// Import resources to register:
import { CloudwatchApiAudit } from "./cloudwatchApiAudit";
import { Foo } from "./foo";
import { Vpc } from "./vpc";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "securebaseline:index:CloudwatchApiAudit":
                return new CloudwatchApiAudit(name, <any>undefined, { urn })
            case "securebaseline:index:Foo":
                return new Foo(name, <any>undefined, { urn })
            case "securebaseline:index:Vpc":
                return new Vpc(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("securebaseline", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("securebaseline", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:securebaseline") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
